### ISSUE TITLE
How about...

### ISSUE THREAD

**Issue by 0x-r4bbit** [OpenWebStack/gruntacular#1]
taking a look at [grunt-testacular](https://github.com/Dignifiedquire/grunt-testacular) and thinking about to merge your great tools? :)

**Comment by geddski** [comment]
Hey @PascalPrecht thanks for dropping by. I did [reach out](https://github.com/Dignifiedquire/grunt-testacular/issues/6#issuecomment-12023754) to that project so we'll see what he would like to do. This is 17 LOC so I'm not super worried about it. The reasons I created this instead of use grunt-testacular are:
- JS is a better fit than CS for my projects
- didn't like the API split into two separate grunt tasks
- had some problems e.g. exiting early before singleRun could do its thing, options getting set on unused variables, etc.

Feel free to use whichever you prefer.

**Comment by 0x-r4bbit** [comment]
I feel you! Thanks!
